name: bonsai 
options: 
  bundleIdPrefix: com.bonsai
targets: 
  bonsai:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: bonsai
    settings:
      base:
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - package: swift-collections
        product: OrderedCollections
packages:
  swift-collections:
    url: https://github.com/apple/swift-collections
    from: 1.0.0
