name: bonsai 
options: 
  bundleIdPrefix: com.bonsai
targets: 
  bonsai:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: bonsai
    info:
      path: bonsai/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Dark
    settings:
      base:
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: swift-collections
        product: OrderedCollections
packages:
  swift-collections:
    url: https://github.com/apple/swift-collections
    from: 1.0.0
