name: bonsai 
options: 
  bundleIdPrefix: com.bonsai
targets: 
  bonsai:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: bonsai
    settings:
      base:
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    info:
      path: bonsai/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
