name: bonsai 
options: 
  bundleIdPrefix: com.bonsai
targets: 
  bonsai:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: bonsai
    info:
      path: bonsai/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Dark
        UIBackgroundModes: [remote-notification]
        UIRequiresFullScreen: YES
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bonsai.tree.app
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    entitlements:
      path: bonsai/bonsai.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers: [iCloud.com.bonsai.tree.app]
        com.apple.developer.icloud-services: [CloudKit]
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
    dependencies:
      - package: swift-collections
        product: OrderedCollections
      - package: purchases-ios
        product: RevenueCat
      - package: LanguageManager-SwiftUI
        product: LanguageManager-SwiftUI
    scheme:
      bonsai:
        - bonsai
  BudgetServiceTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - BudgetServiceTests/
    dependencies:
      - target: bonsai
    scheme:
      testTargets:
        - BudgetServiceTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bonsai.tree.app
        GENERATE_INFOPLIST_FILE: YES
packages:
  swift-collections:
    url: https://github.com/apple/swift-collections
    from: 1.0.0
  purchases-ios:
    url: https://github.com/RevenueCat/purchases-ios
    from: 4.0.0
