name: bonsai 
options: 
    bundleIdPrefix: com.bonsai
targets: 
    bonsai: 
        type: application
        platform: iOS
        deploymentTarget: "14.0"
        sources: bonsai
        settings: 
            GENERATE_INFOPLIST_FILE: true 


